Finish to do list list structure
mustabbas/TodoList pull request #2
Opened 2021-09-22 11:22 UTC by mustabbas

### Change Done
Added a new project with webpack.
Created an index.html file.
Created an index.js file and set an array of some simple to-do tasks (array of objects).
Created a function to iterate over the tasks array and populate an HTML list item element for each task
Created a style.css and set rules for the To-Do List CSS must be loaded by Webpack Style/CSS Loader. Your list should be a clone of the part of the minimalist project captured in the video below.
All your source files (index.html, index.js and style.css) are located in /src directory and distribution files will be generated by webpack and served by webpack dev server from /dist folder.

2021-09-22 12:28 UTC, Lameck1 reviewed
Hi @mustabbas, 

You've put in great effort in building your project. However, this code review request will have to be invalidated. We are the developers of tomorrow, and we are encouraged to practice and abide by industry standards and professionalism.

## Invalid Code Review Request

You have submitted a project, that does not have a professionally documented README. Suggestions are left in the review thread to help with making improvements to the README.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-09-22 12:28 UTC, Lameck1 commented on README.md
> +Follow the steps described before.
- [ ] These are now not necessary if they are pointing us to the details above.

2021-09-22 12:28 UTC, Lameck1 commented on README.md
> +With the files open in Visual Studio Code, press the Go Live button at the bottom of the window to launch the files with Live Server.**
- [ ] Getting started needs improvement, this is not how we get started with a webpack project.

This is the procedure
1. Clone the repo(**tell us how**)
2. Navigate to project's directory(**tell us how**)
3. Install dependencies(**tell us how**)
4. Lastly start the project(**tell us how**)
    Two options here
     - `npm start` on the terminal OR
     - `npm run build` then navigate to build directory and open the index.html file in the browser

2021-09-22 12:29 UTC, Lameck1 commented on README.md
> +- I would like to thank the designer who design this website [Cindy Shin](https://www.behance.net/adagio07) [design guidelines,](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- [ ] This acknowledgment is invalid. Cindy Shin has not participated in this project in any way.

2021-09-23 16:24 UTC, Dipeshtwis requested changes
Hi @mustabbas,

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: configured project with webpack.
👍 The design is looking similar with the given design.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

Check the comments under the review


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Check the comments under the review

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 16:24 UTC, Dipeshtwis commented on src/style.css
> +  /* padding: 5px; */
- [ ] I would recommend removing the commented code to look codebase cleaner.

2021-09-23 16:24 UTC, Dipeshtwis commented on src/index.js
> +  { id: 3, description: '3333333333333', isCompleted: false },
[OPTIONAL]

- Always give meaningful task description to keep the app meaningful.

2021-09-23 16:45 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @mustabbas, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 16:46 UTC, merged